### ISSUE TITLE
Preview not working

### ISSUE THREAD

**Issue by Mortorojo** [alexopus/ComfyUI-Image-Saver#7]
I hope im just missing somthing here, but the image preview in your image saver does not appear to be working.

![Screenshot 2024-01-09 221746 (Small)](https://github.com/alexopus/ComfyUI-Image-Saver/assets/4872869/e6a581a1-fda7-44b9-b3ac-81704f506d6e)

**Comment by alexopus** [comment]
It's because comfy doesn't support saving outside of the output directory. 

Now for some reason this custom node still manages to save the file. Default SaveImage will refuse:

![image](https://github.com/alexopus/ComfyUI-Image-Saver/assets/25933468/ff3bcc54-76f3-4c99-99b9-c04b8fdc5a74)

Afaict there isn't anything I can do about it on the extension side.

If you save within the output dir, you should see the preview.
